AuctionProject/AuctionApp/urls.py
from django.urls import path
from . import views

app_name = 'AuctionApp'

urlpatterns = [
    # Create a path object defining the URL pattern to the index view
    path(route='', view=views.index, name='TradePage'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    path('registration/', views.registration_request, name='registration'),
    path('createauction/', views.create_auction, name='createauction'),
    path('removeauction/<int:auction_id>/', views.remove_auction, name='removeauction'),
]

AuctionProject/AuctionProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('Auction/', include('AuctionApp.urls')),
]

AuctionProject/AuctionApp/models.py
from django.db import models
from django.conf import settings


class Trades(models.Model):
    ItemSell = models.CharField(null=False, max_length=30, default='')
    ItemBuy = models.CharField(null=False, max_length=30, default='')
    Title =  models.CharField(null=False, max_length=15, default='No Title')
    ForSale = models.BooleanField()
    ContactInfo = models.CharField(null=False, max_length=25, default='')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

AuctionProject/AuctionApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from AuctionApp.models import Trades
import logging

logger = logging.getLogger(__name__)


def index(request):
    context = {}
    auctions = Trades.objects.all()
    context['auction_list'] = auctions
    return render(request, 'AuctionApp/auction_view.html', context=context)

def logout_request(request):
    print("Log out the user `{}`".format(request.user.username))

    logout(request)
   
    return redirect('AuctionApp:TradePage')


def login_request(request):
    context = {}
   
    if request.method == "POST":
       
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('AuctionApp:TradePage')
        else:
            return render(request, 'AuctionApp/user_login.html', context)
    else:
        return render(request, 'AuctionApp/user_login.html', context)
    


def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'AuctionApp/user_registration.html', context)
    
    elif request.method == 'POST':
        
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.debug("{} is new user".format(username))
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("AuctionApp:TradePage")
        else:
            return render(request, 'AuctionApp/user_registration.html', context)
        

def create_auction(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'AuctionApp/auction_creation.html', context)
    elif request.method == 'POST':
        if request.user.is_authenticated:
            sellitem = request.POST['sellitem']
            buyitem = request.POST['buyitem']
            Title = request.POST['title']
            contact = request.POST['contact']
            forSale = True
            user = request.user
            trade = Trades(ItemSell=sellitem,ItemBuy=buyitem,Title=Title,ForSale=forSale,user=user,ContactInfo=contact)
            trade.save()
            return redirect("AuctionApp:TradePage")
        
def remove_auction(request,auction_id):
    if request.method == "POST":
        if request.user.is_authenticated:
            auction = get_object_or_404(Trades, id=auction_id)
            if str(auction.user) == str(request.user):
                print("Correct User!")
                auction.ForSale = False
                auction.save()
                return redirect("AuctionApp:TradePage")
                print(auction)
            else:
                print("incorect user")
                return redirect("AuctionApp:TradePage")
            

AuctionProject/AuctionApp/templates/AuctionApp/auction_creation.html
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Online Courses</title>
</head>


<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'AuctionApp:TradePage' %}">Trading Browser!</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
            <h3>Logged in as: {{user.username}}</h2>
            <a href="{% url 'AuctionApp:logout' %}"><buttom class="btn btn-dark">Logout</buttom></a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'AuctionApp:registration' %}"><button class="btn btn-dark">Sign-Up</button></a>
            <a href="{% url 'AuctionApp:login' %}"><button class="btn btn-dark">Login</button></a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>



{% if user.is_authenticated %}
  <form action="{% url 'AuctionApp:createauction' %}" method="post" class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h1 class="text-center">Create Auction</h1>
        <hr>
        
        <div class="mb-3">
          <label for="sellitem" class="form-label"><b>Item to Sell</b></label>
          <input type="text" class="form-control" placeholder="Item" name="sellitem" required>
        </div>
        
        <div class="mb-3">
          <label for="buyitem" class="form-label"><b>Item you want</b></label>
          <input type="text" class="form-control" placeholder="Item" name="buyitem" required>
        </div>
        
        <div class="mb-3">
          <label for="title" class="form-label"><b>Trade Title</b></label>
          <input type="text" class="form-control" placeholder="Title" name="title" required>
        </div>

        <div class="mb-3">
          <label for="contact" class="form-label"><b>Discord</b></label>
          <input type="text" class="form-control" placeholder="Discord Info" name="contact" required>
        </div>
        
        <div>
          {% csrf_token %}
          <button class="btn btn-dark w-100" type="submit">Create</button>
        </div>
      </div>
    </div>
  </form>
{% else %}
  <div class="container mt-5">
    <p>You aren't logged in! Please <a href="{% url 'AuctionApp:login' %}">Login</a> to create an auction.</p>
  </div>
{% endif %}


<!--{% if user.is_authenticated %}
    <form action="{% url 'AuctionApp:createauction' %}"  method="post">
        {% csrf_token %}
          <h1>Create Auction</h1>
          <label for="sellitem"><b>Item to Sell</b></label>
          <input type="text" placeholder="Item" name="sellitem" required>
          <label for="buyitem"><b>Item you want</b></label>
          <input type="text" placeholder="Item" name="buyitem" required>
          <label for="title"><b>Trade Title</b></label>
          <input type="text" placeholder="Disc" name="title" required>
          <div>
            <button class="button" type="submit">Create</button>
          </div>
      </form>
    {% else %}
    you arn't logged in! Please login:
    <a href="{% url 'AuctionApp:login' %}">Login</a>
{% endif %} -->

AuctionProject/AuctionApp/templates/AuctionApp/auction_view.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <meta charset="UTF-8">
        <title>Trading Browser</title>
    </head>
<body>



<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'AuctionApp:TradePage' %}">Trading Browser!</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                
                <h3>Logged in as: {{user.username}}</h2>
                <a href="{% url 'AuctionApp:logout' %}"><buttom class="btn btn-dark">Logout</buttom></a>
                <a href="{% url 'AuctionApp:createauction' %}"><button class="btn btn-dark">Create Auction</button></a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'AuctionApp:registration' %}"><button class="btn btn-dark">Sign-Up</button></a>
                <a href="{% url 'AuctionApp:login' %}"><button class="btn btn-dark">Login</button></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


{% if user.is_authenticated %}
    <h1 class="text-center">Current Trades</h1>
    {% if auction_list %}
    <div class="container">
        <div class="card-deck"> 
            {% for auction in auction_list %}
            {% if auction.ForSale == True %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body bg-light">
                            <h5 class="card-title">{{ auction.Title }}</h5>
                            <p class="card-text"> Item for Sale: {{ auction.ItemSell }}</p>
                            <p class="card-text"> Item Requesting: {{ auction.ItemBuy }}</p>
                            <p class="card-text"> Discord User: {{ auction.ContactInfo }}</p>
                            <!--<a href="{% url 'AuctionApp:removeauction' auction_id=auction.id %}" method="post">{{ auction.user }}</a>-->
                            <p class="card-text">Owner: {{ auction.user }}</p>
                            {% if user.username|stringformat:"s" == auction.user|stringformat:"s" %}
                                <form action="{% url 'AuctionApp:removeauction' auction_id=auction.id %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-dark" type="submit">Remove</button>
                                </form>
                            {% endif %}

                        </div>
                    </div>
                </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% else %}
        Auctions dont exist aww
    {% endif %}
{% else %}
    <div class="d-flex min-vh-100 justify-content-center align-items-center">
        <h2 class="text-center"> Please login to view trades! </h2>
    </div>
{% endif %}
</body>

AuctionProject/AuctionApp/templates/AuctionApp/user_login.html
<head>
  {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <meta charset="UTF-8">
  <title>Online Courses</title>
</head>


<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
      <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'AuctionApp:TradePage' %}">Trading Browser!</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
            <h3>Logged in as: {{user.username}}</h2>
            <a href="{% url 'AuctionApp:logout' %}"><buttom class="btn btn-dark">Logout</buttom></a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'AuctionApp:registration' %}"><button class="btn btn-dark">Sign-Up</button></a>
            <a href="{% url 'AuctionApp:login' %}"><button class="btn btn-dark">Login</button></a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>


<form action="{% url 'AuctionApp:login' %}" method="post" class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">Login</h1>
      <hr>
      <div class="mb-3">
        <label for="username" class="form-label"><b>User Name</b></label>
        <input type="text" class="form-control" placeholder="Enter User Name" name="username" required>
      </div>
      <div class="mb-3">
        <label for="psw" class="form-label"><b>Password</b></label>
        <input type="password" class="form-control" placeholder="Enter Password" name="psw" required>
      </div>
      <div>
        {% csrf_token %}
        <button class="btn btn-dark w-100" type="submit">Login</button>
      </div>
    </div>
  </div>
</form>


<!--
<div class="d-flex min-vh-100 justify-content-center align-items-center">
  <form action="{% url 'AuctionApp:login' %}"  method="post">
    {% csrf_token %}
      <h1 class="text-center">Login</h1>
      <label for="username" ><b>User Name</b></label>
      <input type="text" placeholder="Enter User Name: " name="username" required>
      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password: " name="psw" required>
      <button class="btn btn-dark" type="submit">Login</button>
  </form>
</div>-->

AuctionProject/AuctionApp/templates/AuctionApp/user_registration.html
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Online Courses</title>
</head>



<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'AuctionApp:TradePage' %}">Trading Browser!</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <h3>Logged in as: {{user.username}}</h2>
                <a href="{% url 'AuctionApp:logout' %}"><buttom class="btn btn-dark">Logout</buttom></a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'AuctionApp:registration' %}"><button class="btn btn-dark">Sign-Up</button></a>
                <a href="{% url 'AuctionApp:login' %}"><button class="btn btn-dark">Login</button></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<form action="{% url 'AuctionApp:registration' %}" method="post" class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">Sign Up</h1>
      <hr>
      <div class="mb-3">
        <label for="username" class="form-label"><b>User Name</b></label>
        <input type="text" class="form-control" placeholder="Enter User Name" name="username" required>
      </div>
      <div class="mb-3">
        <label for="firstname" class="form-label"><b>First Name</b></label>
        <input type="text" class="form-control" placeholder="Enter First Name" name="firstname" required>
      </div>
      <div class="mb-3">
        <label for="lastname" class="form-label"><b>Last Name</b></label>
        <input type="text" class="form-control" placeholder="Enter Last Name" name="lastname" required>
      </div>
      <div class="mb-3">
        <label for="psw" class="form-label"><b>Password</b></label>
        <input type="password" class="form-control" placeholder="Enter Password" name="psw" required>
      </div>
      <div>
        {% csrf_token %}
        <button class="btn btn-dark w-100" type="submit">Sign Up</button>
      </div>
    </div>
  </div>
</form>

<!--<form action="{% url 'AuctionApp:registration' %}" method="post">
    <h1>Sign Up</h1>
    <hr>
    <label for="username"><b>User Name</b></label>
    <input type="text" placeholder="Enter User Name: " name="username" required>
    <label for="firstname"><b>First Name</b></label>
    <input type="text" placeholder="Enter First Name: " name="firstname" required>
    <label for="lastname"><b>Last Name</b></label>
    <input type="text" placeholder="Enter Last Name: " name="lastname" required>
    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password: " name="psw" required>
    <div>
        {% csrf_token %}
        <button class="button" type="submit">Sign Up</button>
    </div>
</form>-->